services:
  aurora-test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=aurora_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres