services:
  aurora:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    depends_on:
      - postgres
    ports:
      - "80:80"
    restart: on-failure
  karton:
    build:
      context: kartons
      dockerfile: Dockerfile
  minhash:
    build:
      context: kartons
      dockerfile: kartons/minhash/Dockerfile
  similarity:
    build:
      context: kartons
      dockerfile: kartons/similarity/Dockerfile
  strings:
    build:
      context: kartons
      dockerfile: kartons/strings/Dockerfile
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - /tmp/minio:/data
