services:
  aurora:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "80:80"
    restart: on-failure
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
  redis:
    image: redis:alpine
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - /tmp/minio:/data
  karton-system:
    image: certpl/karton-system:master
    depends_on:
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini
    entrypoint: karton-system
    command: --setup-bucket
  karton-dashboard:
    image: certpl/karton-dashboard:5caecf96d6363b13d37848cadcaab408d8b50565
    depends_on:
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini
    ports:
      - "5000:5000"
  karton-classifier:
    build:
      context: ./kartons/karton-classifier/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini
  karton-minhash:
    build:
      context: ./kartons/karton-minhash/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini
  karton-r2disasm:
    build:
      context: ./kartons/karton-r2disasm
      dockerfile: Dockerfile
    depends_on:
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini
  karton-similarity:
    restart: on-failure
    build:
      context: ./kartons/karton-similarity/
      dockerfile: Dockerfile
    depends_on:
      - aurora
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini
  karton-strings-extractor:
    build:
      context: ./kartons/karton-strings-extractor/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini
  karton-strings-scanner:
    build:
      context: ./kartons/karton-strings-scanner/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - minio
    volumes:
      - ./karton.ini:/etc/karton/karton.ini